<?php
echo "Hello RAN Demand Management";

curl -X POST \-H 'Content-Type:application/json' \-H 'Authorization: Bearer {yljVPwAACVbpoFQBCmMKwJlmk3Pe4J9pqqKOHGQ9WhRqiuEcM+J7A0VzgPDDxuuvfHMdyis34vIzWIXZ19poQVbQxTRQGTMfEAyxsCCzmMOE9WChL3EP42q8iNQLJPXe3HVEMO/wPn6JXALbxe2MSQdB04t89/1O/w1cDnyilFU=}' \...

curl -X GET \-H 'Authorization: Bearer {yljVPwAACVbpoFQBCmMKwJlmk3Pe4J9pqqKOHGQ9WhRqiuEcM+J7A0VzgPDDxuuvfHMdyis34vIzWIXZ19poQVbQxTRQGTMfEAyxsCCzmMOE9WChL3EP42q8iNQLJPXe3HVEMO/wPn6JXALbxe2MSQdB04t89/1O/w1cDnyilFU=}' \https://api.line.me/v1/oauth/verify

<?php$access_token = 'yljVPwAACVbpoFQBCmMKwJlmk3Pe4J9pqqKOHGQ9WhRqiuEcM+J7A0VzgPDDxuuvfHMdyis34vIzWIXZ19poQVbQxTRQGTMfEAyxsCCzmMOE9WChL3EP42q8iNQLJPXe3HVEMO/wPn6JXALbxe2MSQdB04t89/1O/w1cDnyilFU=';$url = 'https://api.line.me/v1/oauth/verify';$headers = array('Authorization: Bearer ' . $access_token);$ch = curl_init($url);curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);$result = curl_exec($ch);curl_close($ch);echo $result;
{  "events": [      {        "replyToken": "nHuyWiB7yP5Zw52FIkcQobQuGDXCTA",        "type": "message",        "timestamp": 1462629479859,        "source": {             "type": "user",             "userId": "U206d25c2ea6bd87c17655609a1c37cb8"         },         "message": {             "id": "325708",             "type": "text",             "text": "Hello, world"          }      }  ]}

<?php$access_token = 'yljVPwAACVbpoFQBCmMKwJlmk3Pe4J9pqqKOHGQ9WhRqiuEcM+J7A0VzgPDDxuuvfHMdyis34vIzWIXZ19poQVbQxTRQGTMfEAyxsCCzmMOE9WChL3EP42q8iNQLJPXe3HVEMO/wPn6JXALbxe2MSQdB04t89/1O/w1cDnyilFU=';// Get POST body content$content = file_get_contents('php://input');// Parse JSON$events = json_decode($content, true);// Validate parsed JSON dataif (!is_null($events['events'])) {	// Loop through each event	foreach ($events['events'] as $event) {		// Reply only when message sent is in 'text' format		if ($event['type'] == 'message' && $event['message']['type'] == 'text') {			// Get text sent			$text = $event['message']['text'];			// Get replyToken			$replyToken = $event['replyToken'];			// Build message to reply back			$messages = [				'type' => 'text',				'text' => $text			];			// Make a POST Request to Messaging API to reply to sender			$url = 'https://api.line.me/v2/bot/message/reply';			$data = [				'replyToken' => $replyToken,				'messages' => [$messages],			];			$post = json_encode($data);			$headers = array('Content-Type: application/json', 'Authorization: Bearer ' . $access_token);			$ch = curl_init($url);			curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");			curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);			curl_setopt($ch, CURLOPT_POSTFIELDS, $post);			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);			curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);			$result = curl_exec($ch);			curl_close($ch);			echo $result . "";		}	}}echo "OK";
